SELECT F.ID, JF.FISH_NAME, JF.LENGTH
FROM FISH_INFO F, (SELECT F.FISH_TYPE, FN.FISH_NAME, MAX(F.LENGTH) AS LENGTH
FROM FISH_INFO AS F INNER JOIN FISH_NAME_INFO AS FN ON F.FISH_TYPE = FN.FISH_TYPE
GROUP BY F.FISH_TYPE, FN.FISH_NAME) JF
WHERE F.FISH_TYPE = JF.FISH_TYPE AND F.LENGTH = JF.LENGTH
ORDER BY F.ID ASC